### ISSUE TITLE
AlexNet model

### ISSUE THREAD

**Issue by deep0learning** [jihanyang/AFN#1]
Hi, 
May I know that how we can test the results with Alexnet model? It would be really nice if you compare your results with Alexnet model?

Thanks and regards,

**Comment by Ruijia-Xu** [comment]
Hi @deep0learning,
Thanks for your interest in the project. We don't have plan to implement this in the near future, as we are trying to do fair comparisons against those emerging works with the identical backbone network and deep learning framework. If you are interested to try that, pay attention to the framework (Caffe) and pre-trained model (BAIR Reference CaffeNet) that are usually used.

**Comment by redhat12345** [comment]
May I get the code for Alexnet?
