### ISSUE TITLE
about "ResClassifier" in the framework

### ISSUE THREAD

**Issue by Zysty** [jihanyang/AFN#12]
Hi, thanks for your sharing the code!
As shown in the AFN/vanilla/Visda2017/SAFN/code/model/net.py ,  the "ResClassifier" contains three FC layers with 2048 * 1000, 1000 * 1000, 1000 * class_num neurons, respectively. While as shown in the AFN/vanilla/Office31/SAFN/code/model/net.py /, the "ResClassifier " contains two FC layers with 2048 * 1000, and 1000 * class_num neurons, respectively.
1. Could you explain that why the "ResClassifier" has diffirent  FC layers in diffirent datasets? 
2.  As shown in Table 1,  CDAN is one of the compaired models. But as far as I know, the corresponding "ResClassifier" in CDAN has two FC layers with 2048 * 256, and 256 * class_num neurons in all datasets, respectively.  It's unclear to show the superiority of the proposed methods because the increase of parameters can also obtain some gain. Do you have additional experimental results about the model has the same "ResClassifer" ?
By the way,  according to the  section 3.3 in the paper,   you cited literature [7, 26] in paper to illustrate the so-called bottleneck. But in the respository of  [7] ,  I find the description in the corresponding code that [7] has the same "ResClassifer" as CDAN.

**Comment by jihanyang** [comment]
Hello,
1. Our ResClassifier architectures are similar to them in MCD_DA for different datasets.
2. About the setting of our experiments, please contact the first author Ruijia Xu.

**Comment by Ruijia-Xu** [comment]
Hello,

(1) Actually, as you can find in Figure 3(d), we have conducted an ablation study about the "Sensitivity of Embedding Size", you can check there.
(2) As said by Jihan, we followed MCD_DA and applied two fully-connected layers, each has 1000 neurons, as the bottleneck in the classifier on VisDA2017. Considering small sample size of other
benchmarks, we reduced bottleneck to one fully-connected layer. 

Thanks again for your interest.

**Comment by Zysty** [comment]
OK. Thanks for your reply.
