### ISSUE TITLE
Asking for Visualization Code

### ISSUE THREAD

**Issue by taylover-pei** [jihanyang/AFN#6]
You have done a great work.

I am confused that whether you can publish the codes about visualization in figure 1 and figure 4?

Thank you very much. Looking forward to your replay.

**Comment by jihanyang** [comment]
Hello, I have graduated from Sun Yat-sen University and cannot touch any code from the servers. As for the visualization in figure 1, you can contact the first author of our paper. And we use t-sne in sklearn for figure 4. You can access sufficient documents about how to use it. Hope my answer is useful for you.
